#!/usr/bin/env python3
"""Render compact LaTeX evidence assets from the frozen canonical export."""

from __future__ import annotations

import csv
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = Path(os.environ.get("BENCHMARK_EVAL_ROOT", ROOT.parent / "benchmark_eval")).expanduser().resolve()
SOURCE = SOURCE_ROOT / "notebooks" / "canonical_evidence_export"
MONITORING_COST_SOURCE = SOURCE_ROOT / "assets" / "drift" / "monitoring_cost.json"
TARGET = ROOT / "assets" / "metrics_export"
FIGURE_TARGET = ROOT / "assets" / "evidence"
FIGURE_STEMS = (
    "fig_canonical_monitoring_trajectory",
    "fig_canonical_mcnemar_matrix",
    "fig_canonical_power_heatmap",
    "fig_canonical_cost_decision_map",
    "fig_canonical_gepa_effects",
    "fig_canonical_disagreement_matrix",
)
DATA_EXPORTS = (
    "canonical_disagreement_matrix_source.csv",
    "canonical_disagreement_matrix_summary.json",
)


def fmt(value: float, digits: int = 3) -> str:
    return f"{value:.{digits}f}"


def write(path: Path, text: str) -> None:
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def load_csv(name: str) -> list[dict[str, str]]:
    with (SOURCE / name).open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def main() -> None:
    if not SOURCE.exists():
        raise FileNotFoundError(
            f"Canonical evidence export not found at {SOURCE}. "
            "Set BENCHMARK_EVAL_ROOT to point at the code/repro repository checkout."
        )
    subprocess.run(
        [sys.executable, str(SOURCE_ROOT / "make_canonical_figures.py")],
        check=True,
    )
    subprocess.run(
        [sys.executable, str(SOURCE_ROOT / "make_disagreement_figure.py")],
        check=True,
    )
    summary = json.loads((SOURCE / "canonical_summary.json").read_text(encoding="utf-8"))
    monitoring = summary["monitoring"]
    trigger = monitoring["trigger_rows"][0]
    power = summary["power"]
    cost = summary["cost"]
    monitoring_cost = json.loads(MONITORING_COST_SOURCE.read_text(encoding="utf-8"))

    write(
        TARGET / "canonical_macros.tex",
        "\n".join(
            [
                "% Generated by scripts/sync_canonical_evidence.py; do not edit.",
                rf"\providecommand{{\CanonicalVersion}}{{{summary['analysis_version']}}}",
                rf"\providecommand{{\CanonicalRuns}}{{{monitoring['eligible_runs']}}}",
                rf"\providecommand{{\CanonicalModels}}{{{monitoring['models']}}}",
                rf"\providecommand{{\CanonicalComparisons}}{{{monitoring['comparisons']}}}",
                rf"\providecommand{{\CanonicalRawSignificant}}{{{monitoring['raw_significant']}}}",
                rf"\providecommand{{\CanonicalHolmAlerts}}{{{monitoring['holm_significant']}}}",
                rf"\providecommand{{\CanonicalAlertPairs}}{{{trigger['n_pairs']}}}",
                rf"\providecommand{{\CanonicalAlertB}}{{{trigger['b_degrade']}}}",
                rf"\providecommand{{\CanonicalAlertC}}{{{trigger['c_improve']}}}",
                rf"\providecommand{{\CanonicalAlertDrop}}{{{abs(trigger['delta']) * 100:.1f}}}",
                rf"\providecommand{{\CanonicalCostN}}{{{cost['common_n']}}}",
                rf"\providecommand{{\CanonicalCostWinner}}{{\texttt{{{cost['winner']}}}}}",
            ]
        ),
    )

    write(
        TARGET / "canonical_monitoring_summary.tex",
        "\n".join(
            [
                "% Generated from canonical_summary.json; do not edit.",
                r"\begin{tabular}{lr}",
                r"\toprule",
                r"Quantity & Value \\",
                r"\midrule",
                rf"Eligible scheduled runs & {monitoring['eligible_runs']} \\",
                rf"Models with comparisons & {monitoring['models']} \\",
                rf"Baseline-to-later comparisons & {monitoring['comparisons']} \\",
                rf"Nominal one-sided \(p<0.05\) & {monitoring['raw_significant']} \\",
                r"\bottomrule",
                r"\end{tabular}",
            ]
        ),
    )

    reference_rows = [
        row
        for row in load_csv("exact_unconditional_power_sensitivity.csv")
        if row["scope"] == "design_grid" and row["model"] == "rho=0.12"
    ]
    if len(reference_rows) != 1:
        raise RuntimeError("expected exactly one rho=0.12 design row")
    row = reference_rows[0]
    write(
        TARGET / "canonical_power_summary.tex",
        "\n".join(
            [
                "% Generated from exact_unconditional_power_sensitivity.csv; do not edit.",
                r"\begin{tabular}{lrrr}",
                r"\toprule",
                rf"Threshold & 80\% MDE & Power at 5pp & Power at 8pp \\",
                r"\midrule",
                rf"Nominal \(\alpha=0.05\) & {float(row['nominal_g_80']) * 100:.2f}pp & {float(row['nominal_power_at_5pp']):.3f} & {float(row['nominal_power_at_8pp']):.3f} \\",
                rf"Conservative \(\alpha=0.05/{monitoring['comparisons']}\) & {float(row['family_g_80']) * 100:.2f}pp & {float(row['family_power_at_5pp']):.3f} & {float(row['family_power_at_8pp']):.3f} \\",
                r"\bottomrule",
                r"\end{tabular}",
            ]
        ),
    )

    def tex_p(value: float) -> str:
        if value >= 0.999:
            return "1"
        if value >= 0.001:
            return f"{value:.4f}"
        exponent = int(f"{value:.3e}".split("e")[1])
        coef = value / (10**exponent)
        return rf"{coef:.3f}\times10^{{{exponent}}}"

    def tex_day(stamp: str) -> str:
        months = {
            "01": "Jan",
            "02": "Feb",
            "03": "Mar",
            "04": "Apr",
            "05": "May",
            "06": "Jun",
            "07": "Jul",
            "08": "Aug",
            "09": "Sep",
            "10": "Oct",
            "11": "Nov",
            "12": "Dec",
        }
        year, month, day = stamp[:10].split("-")
        return f"{int(day)}~{months[month]}"

    all_comparisons = load_csv("baseline_to_later_mcnemar.csv")
    nominal_rows = [row for row in all_comparisons if float(row["p_down"]) < 0.05]
    nominal_rows.sort(key=lambda row: float(row["p_down"]))
    if len(nominal_rows) != 3:
        raise RuntimeError(f"expected 3 nominal comparisons, got {len(nominal_rows)}")
    nominal_blocks: list[str] = []
    for item in nominal_rows:
        n_pairs = int(item["n_pairs"])
        b_count = int(item["b_degrade"])
        a_count = int(round(float(item["acc_baseline"]) * n_pairs)) - b_count
        c_count = int(item["c_improve"])
        d_count = n_pairs - a_count - b_count - c_count
        if min(a_count, d_count) < 0:
            raise RuntimeError(f"invalid 2x2 reconstruction for {item['model']}")
        delta_pp = float(item["delta"]) * 100
        delta_tex = f"{delta_pp:.1f}" if abs(delta_pp) >= 10 else f"{delta_pp:.2f}"
        window = f"{tex_day(item['baseline_started'])}--{tex_day(item['later_started'])}"
        nominal_blocks.append(
            "\n".join(
                [
                    r"\begin{minipage}[t]{0.32\linewidth}",
                    r"\centering",
                    rf"\texttt{{{item['model']}}}\\",
                    rf"{{\scriptsize {window}, \(n={n_pairs}\)}}\\[3pt]",
                    r"\begin{tabular}{c|cc}",
                    r" & later \(+\) & later \(-\) \\",
                    r"\hline",
                    rf"base \(+\) & {a_count} & \(b={b_count}\) \\",
                    rf"base \(-\) & \(c={c_count}\) & {d_count} \\",
                    r"\end{tabular}\\[3pt]",
                    rf"{{\scriptsize \(\Delta={delta_tex}\)\,pp, \(p_{{\mathrm{{exact}}}}={tex_p(float(item['p_down']))}\)}}",
                    r"\end{minipage}",
                ]
            )
        )
    write(
        TARGET / "canonical_nominal_comparisons.tex",
        "\n".join(
            [
                "% Generated from baseline_to_later_mcnemar.csv; do not edit.",
                nominal_blocks[0],
                r"\hfill",
                nominal_blocks[1],
                r"\hfill",
                nominal_blocks[2],
            ]
        ),
    )

    cost_rows = load_csv("deployment_cost_may22.csv")
    lines = [
        "% Generated from deployment_cost_may22.csv; do not edit.",
        r"\begin{tabular}{lrrrrrrr}",
        r"\toprule",
        r"Model & Accuracy & Precision & Recall & $c_t(m)$ (USD) & FP & FN & Loss \\",
        r"\midrule",
    ]
    for item in cost_rows:
        precision = float(item["TP"]) / (float(item["TP"]) + float(item["FP"]))
        lines.append(
            rf"\texttt{{{item['model']}}} & {fmt(float(item['accuracy']))} & "
            rf"{fmt(precision)} & {fmt(float(item['recall']))} & "
            rf"{fmt(float(item['mean_cost']), 4)} & {item['FP']} & {item['FN']} & "
            rf"{fmt(float(item['expected_cost']), 4)} \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    write(TARGET / "canonical_cost_summary.tex", "\n".join(lines))

    write(
        TARGET / "monitoring_cost_summary.tex",
        "\n".join(
            [
                "% Generated from assets/drift/monitoring_cost.json; do not edit.",
                r"\begin{tabular}{lrr}",
                r"\toprule",
                r"Evaluation scope & Eight models & Three production models \\",
                r"\midrule",
                rf"Full benchmark & \${monitoring_cost['benchmark_usd']:.2f} & "
                rf"\${monitoring_cost['production_benchmark_usd']:.2f} \\",
                rf"Sentinel panel & \${monitoring_cost['panel_usd']:.2f} & "
                rf"\${monitoring_cost['production_panel_usd']:.2f} \\",
                r"\bottomrule",
                r"\end{tabular}",
            ]
        ),
    )

    scenario_lines = [
        "% Generated from assets/drift/monitoring_cost.json; do not edit.",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Model & Panel & Full & Annual panel & Weekly break-even \\",
        r"\midrule",
    ]
    for model in monitoring_cost["production_models"]:
        item = monitoring_cost["production_model_scenarios"][model]
        scenario_lines.append(
            rf"\texttt{{{model}}} & \${item['panel_usd']:.2f} & "
            rf"\${item['benchmark_usd']:.2f} & "
            rf"\${item['weekly_panel_annual_usd']:.2f} & "
            rf"{item['weekly_break_even_affected_items']} posts \\"
        )
    scenario_lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
        ]
    )
    write(TARGET / "production_monitoring_scenarios.tex", "\n".join(scenario_lines))

    FIGURE_TARGET.mkdir(parents=True, exist_ok=True)
    for stem in FIGURE_STEMS:
        for suffix in (".pdf", ".png"):
            shutil.copy2(SOURCE / f"{stem}{suffix}", FIGURE_TARGET / f"{stem}{suffix}")
    for name in DATA_EXPORTS:
        shutil.copy2(SOURCE / name, TARGET / name)

    print(
        json.dumps(
            {
                "source": str(SOURCE),
                "version": summary["analysis_version"],
                "generated": [
                    "canonical_macros.tex",
                    "canonical_monitoring_summary.tex",
                    "canonical_power_summary.tex",
                    "canonical_nominal_comparisons.tex",
                    "canonical_cost_summary.tex",
                    "monitoring_cost_summary.tex",
                    "production_monitoring_scenarios.tex",
                    *DATA_EXPORTS,
                    *[f"{stem}.pdf" for stem in FIGURE_STEMS],
                ],
                "reference_rho": power["reference_rho"],
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
